# Generated by Django 5.2.17 on 2026-08-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionwebsite',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_websites', to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatsessionwebsite',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='websites.website'),
        ),
    ]
