# Generated by Django 5.2.17 on 2026-09-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsessionwebsite_chat_session_and_more'),
        ('documents', '0002_remove_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_documents', to='chat.chatsession')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='documents',
            field=models.ManyToManyField(through='chat.ChatSessionDocument', to='documents.document'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiondocument',
            constraint=models.UniqueConstraint(fields=('chat_session', 'document'), name='unique_chat_document'),
        ),
    ]
