# Generated by Django 5.2.17 on 2026-09-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_crawl_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_user_website',
        ),
    ]
